---
title: ""
geometry: "left=2cm,right=2cm,top=1.25cm,bottom=1.25cm"
output:
  pdf_document: default
  word_document: default
fontsize: 10pt
---

\pagenumbering{gobble}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(gtsummary)
library(flextable)
library(tidyverse)
library(serosurvr)
library(countrycode)
```

```{r}
script_path = "scripts/"
data_path = "data/"

source("scripts/plot_waves.R")
```

### Eastern Africa

```{r Eastern_Africa, results='hide', fig.keep='all', fig.height = 4, fig.width = 10}
plot_waves("Eastern Africa")
```

### Southern Africa

```{r Southern_Africa, results='hide', fig.keep='all', fig.height = 4, fig.width = 10}
plot_waves("Southern Africa")
```

### Western Africa

```{r Western_Africa, results='hide', fig.keep='all', fig.height = 4, fig.width = 10}
plot_waves("Western Africa")
```

### Middle Africa

```{r Middle_Africa, results='hide', fig.keep='all', fig.height = 4, fig.width = 10}
plot_waves("Middle Africa")
```

```{r}
pdf("figures/Figure 2_all.pdf",height=4,width=10)
plot_waves("Eastern Africa")
plot_waves("Southern Africa")
plot_waves("Western Africa")
plot_waves("Middle Africa")

dev.off()

pdf("figures/Figure 2_selected.pdf",height=4,width=10)
who_sero_data <- who_sero_data %>%
  mutate(subregion=if_else(country %in% c("Kenya", "Malawi"),
                           "Selected Countries 1", subregion))
plot_waves("Selected Countries 1")
who_sero_data <- who_sero_data %>%
  mutate(subregion=if_else(country %in% c("Ghana", "South Africa"),
                           "Selected Countries 2", subregion))
plot_waves("Selected Countries 2")
dev.off()
```

